src/main/java/com/ashsmagicshop/boundary/cdi/controller/CustomerOrderController.java
package com.ashsmagicshop.boundary.cdi.controller;

import com.ashsmagicshop.entity.CustomerOrder;
import com.ashsmagicshop.boundary.cdi.controller.util.JsfUtil;
import com.ashsmagicshop.control.jsf.view.PaginationHelper;
import com.ashsmagicshop.boundary.facade.CustomerOrderFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import javax.faces.bean.ManagedBean;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;

@Named("customerOrderController")
@SessionScoped
public class CustomerOrderController implements Serializable {

    private CustomerOrder current;
    private DataModel items = null;
    @Inject
    private com.ashsmagicshop.boundary.facade.CustomerOrderFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private String view;
    private String outcome;
    private int page;
    private int pageSize;
    private int numberOfPages;
    private String sortOrder;
    private String orderByField;
    
    @Inject
    Conversation convo;
    
    @Inject
    private transient Logger log;

    public CustomerOrderController() {
    }
    
    @PostConstruct
    public void init(){
        log.fine("init called");
        convo.begin();
        this.setView("List.xhtml");
        this.setOutcome("customerOrder");
        this.setPage(1);
        this.setPageSize(10);
        this.setSortOrder("desc");
        this.setOrderByField("customerorderId");
    }

    public CustomerOrder getSelected() {
        if (current == null) {
            current = new CustomerOrder();
            selectedItemIndex = -1;
        }
        return current;
    }

    private CustomerOrderFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        log.fine("getPagination");
        if (pagination == null) {
            log.fine("paginationNull");
            pagination = new PaginationHelper(page-1,pageSize) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    int lastRangeItem = getPageFirstItem() + getPageSize()-1;
                    if(getPageFirstItem() == 0){
                        lastRangeItem = pageSize-1;
                    }
                    log.fine("listDataModel:" + sortOrder);
                    
                    return new ListDataModel(
                            getFacade().findRange(new int[]{getPageFirstItem(), lastRangeItem},
                                    sortOrder,
                                    orderByField));
                }
            };
        }
        //casting the ints to doubles is important!
        //.5s weren't rounding up without it
        double numberOfPages = Math.round( ((double)pagination.getItemsCount()/ (double)pageSize));
        setNumberOfPages((int) numberOfPages);
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (CustomerOrder) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        setView("View.xhtml");
        return "index";
    }

    public String prepareCreate() {
        current = new CustomerOrder();
        selectedItemIndex = -1;
        setView("Create.xhtml");
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/customerOrder").getString("CustomerOrderCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/customerOrder").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (CustomerOrder) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        this.setView("Edit.xhtml");
        return "customerOrder";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/customerOrder").getString("CustomerOrderUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/customerOrder").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (CustomerOrder) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/customerOrder").getString("CustomerOrderDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/customerOrder").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public CustomerOrder getCustomerOrder(java.lang.Integer id) {
        return ejbFacade.find(id);
    }
    
    public List<CustomerOrder> getCustomerOrders(String field, String sortOrder){
        return ejbFacade.getCustomerOrders("c.customerOrderId", "DESC");
       
    }

    public String getView() {
        return view;
    }

    public void setView(String view) {
        this.view = view;
    }
    
    public void viewAction(){
        log.fine("content:" + this.view);
        log.fine("page:" + this.page);
        getPagination().setPage(page-1);
        log.fine("getPagination.getPage:" + getPagination().getPage());
        items = getPagination().createPageDataModel();
    }
    
    public String getOutcome() {
        return outcome;
    }

    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }

    public int getPage() {
        return page;
    }

    public void setPage(int page) {
        this.page = page;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    public int getNumberOfPages() {
        return numberOfPages;
    }

    public void setNumberOfPages(int numberOfPages) {
        this.numberOfPages = numberOfPages;
    }
    
     public Conversation getConvo() {
        return convo;
    }

    public void setConvo(Conversation convo) {
        this.convo = convo;
    }

    public String getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(String sortOrder) {
        this.sortOrder = sortOrder;
    }

    public String getOrderByField() {
        return orderByField;
    }

    public void setOrderByField(String orderByField) {
        this.orderByField = orderByField;
    }
    
    
    @FacesConverter(forClass = CustomerOrder.class)
    public static class CustomerOrderControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CustomerOrderController controller = (CustomerOrderController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "customerOrderController");
            return controller.getCustomerOrder(getKey(value));
        }

        java.lang.Integer getKey(String value) {

src/main/webapp/admin/shop/customerOrder/customerOrder/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{customerOrder.CreateCustomerOrderTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_customerorderId}" for="customerorderId" />
                    <h:inputText id="customerorderId" value="#{customerOrderController.selected.customerorderId}" title="#{customerOrder.CreateCustomerOrderTitle_customerorderId}" required="true" requiredMessage="#{customerOrder.CreateCustomerOrderRequiredMessage_customerorderId}"/>
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_customerId}" for="customerId" />
                    <h:inputText id="customerId" value="#{customerOrderController.selected.customerId}" title="#{customerOrder.CreateCustomerOrderTitle_customerId}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_orderDate}" for="orderDate" />
                    <h:inputText id="orderDate" value="#{customerOrderController.selected.orderDate}" title="#{customerOrder.CreateCustomerOrderTitle_orderDate}" required="true" requiredMessage="#{customerOrder.CreateCustomerOrderRequiredMessage_orderDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_billTofirstName}" for="billTofirstName" />
                    <h:inputText id="billTofirstName" value="#{customerOrderController.selected.billTofirstName}" title="#{customerOrder.CreateCustomerOrderTitle_billTofirstName}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_billTolastName}" for="billTolastName" />
                    <h:inputText id="billTolastName" value="#{customerOrderController.selected.billTolastName}" title="#{customerOrder.CreateCustomerOrderTitle_billTolastName}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_billToemailAddress}" for="billToemailAddress" />
                    <h:inputText id="billToemailAddress" value="#{customerOrderController.selected.billToemailAddress}" title="#{customerOrder.CreateCustomerOrderTitle_billToemailAddress}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_billingAddress}" for="billingAddress" />
                    <h:selectOneMenu id="billingAddress" value="#{customerOrderController.selected.billingAddress}" title="#{customerOrder.CreateCustomerOrderTitle_billingAddress}" >
                        <f:selectItems value="#{addressController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_shipTofirstName}" for="shipTofirstName" />
                    <h:inputText id="shipTofirstName" value="#{customerOrderController.selected.shipTofirstName}" title="#{customerOrder.CreateCustomerOrderTitle_shipTofirstName}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_shipTolastName}" for="shipTolastName" />
                    <h:inputText id="shipTolastName" value="#{customerOrderController.selected.shipTolastName}" title="#{customerOrder.CreateCustomerOrderTitle_shipTolastName}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_subTotal}" for="subTotal" />
                    <h:inputText id="subTotal" value="#{customerOrderController.selected.subTotal}" title="#{customerOrder.CreateCustomerOrderTitle_subTotal}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_taxAmount}" for="taxAmount" />
                    <h:inputText id="taxAmount" value="#{customerOrderController.selected.taxAmount}" title="#{customerOrder.CreateCustomerOrderTitle_taxAmount}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_shippingCharge}" for="shippingCharge" />
                    <h:inputText id="shippingCharge" value="#{customerOrderController.selected.shippingCharge}" title="#{customerOrder.CreateCustomerOrderTitle_shippingCharge}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_grandTotal}" for="grandTotal" />
                    <h:inputText id="grandTotal" value="#{customerOrderController.selected.grandTotal}" title="#{customerOrder.CreateCustomerOrderTitle_grandTotal}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_promotionCode}" for="promotionCode" />
                    <h:inputText id="promotionCode" value="#{customerOrderController.selected.promotionCode}" title="#{customerOrder.CreateCustomerOrderTitle_promotionCode}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_orderStatusId}" for="orderStatusId" />
                    <h:inputText id="orderStatusId" value="#{customerOrderController.selected.orderStatusId}" title="#{customerOrder.CreateCustomerOrderTitle_orderStatusId}" />
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_shippingService}" for="shippingService" />
                    <h:selectOneMenu id="shippingService" value="#{customerOrderController.selected.shippingService}" title="#{customerOrder.CreateCustomerOrderTitle_shippingService}" >
                        <f:selectItems value="#{shippingServiceController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{customerOrder.CreateCustomerOrderLabel_comments}" for="comments" />
                    <h:inputText id="comments" value="#{customerOrderController.selected.comments}" title="#{customerOrder.CreateCustomerOrderTitle_comments}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{customerOrderController.create}" value="#{customerOrder.CreateCustomerOrderSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{customerOrderController.prepareList}" value="#{customerOrder.CreateCustomerOrderShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{customerOrder.CreateCustomerOrderIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

src/main/webapp/admin/shop/customerOrder/customerOrder/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/WEB-INF/templates/admin/templateSbAdmin.xhtml">
        <ui:define name="title">
            <h:outputText value="#{customerOrder.ListCustomerOrderTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <div class="panel panel-default">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{customerOrder.ListCustomerOrderEmpty}" rendered="#{customerOrderController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{customerOrderController.items.rowCount > 0}">
                    <h:outputText value="#{customerOrderController.pagination.pageFirstItem + 1}..#{customerOrderController.pagination.pageLastItem + 1}/#{customerOrderController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{customerOrderController.previous}" value="#{customerOrder.Previous} #{customerOrderController.pagination.pageSize}" rendered="#{customerOrderController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{customerOrderController.next}" value="#{customerOrder.Next} #{customerOrderController.pagination.pageSize}" rendered="#{customerOrderController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{customerOrderController.items}" 
                                 var="item" 
                                 border="0" 
                                 cellpadding="2" 
                                 cellspacing="0" 
                                 rowClasses="jsfcrud_odd_row,jsfcrud_even_row"
                                 rules="all" 
                                 styleClass="table table-hover">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_customerorderId}"/>
                            </f:facet>
                            <h:outputText value="#{item.customerorderId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_customerId}"/>
                            </f:facet>
                            <h:outputText value="#{item.customerId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_orderDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.orderDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_billTofirstName}"/>
                            </f:facet>
                            <h:outputText value="#{item.billTofirstName}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_billTolastName}"/>
                            </f:facet>
                            <h:outputText value="#{item.billTolastName}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_billToemailAddress}"/>
                            </f:facet>
                            <h:outputText value="#{item.billToemailAddress}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_billingAddress}"/>
                            </f:facet>
                            <h:outputText value="#{item.billingAddress}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_shipTofirstName}"/>
                            </f:facet>
                            <h:outputText value="#{item.shipTofirstName}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_shipTolastName}"/>
                            </f:facet>
                            <h:outputText value="#{item.shipTolastName}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_subTotal}"/>
                            </f:facet>
                            <h:outputText value="#{item.subTotal}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_taxAmount}"/>
                            </f:facet>
                            <h:outputText value="#{item.taxAmount}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_shippingCharge}"/>
                            </f:facet>
                            <h:outputText value="#{item.shippingCharge}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_grandTotal}"/>
                            </f:facet>
                            <h:outputText value="#{item.grandTotal}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_promotionCode}"/>
                            </f:facet>
                            <h:outputText value="#{item.promotionCode}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_orderStatusId}"/>
                            </f:facet>
                            <h:outputText value="#{item.orderStatusId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_shippingService}"/>
                            </f:facet>
                            <h:outputText value="#{item.shippingService}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{customerOrder.ListCustomerOrderTitle_comments}"/>
                            </f:facet>
                            <h:outputText value="#{item.comments}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{customerOrderController.prepareView}" value="#{customerOrder.ListCustomerOrderViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{customerOrderController.prepareEdit}" value="#{customerOrder.ListCustomerOrderEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{customerOrderController.destroy}" value="#{customerOrder.ListCustomerOrderDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{customerOrderController.prepareCreate}" value="#{customerOrder.ListCustomerOrderCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{customerOrder.ListCustomerOrderIndexLink}"/>
            </h:form>
            </div>
        </ui:define>
    </ui:composition>

</html>